config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :recommendations, only: [ :show, :index, :edit, :update, :new, :create] do
    collection do
      get :searched
      get :viewed
      get :to_view
    end

    member do
      get :add_friend_reco
    end

    get 'movies_search', to: "recommendations#movies_search", as: :movies_search
  end

  resources :bookrecoms, only: [ :show, :index, :edit, :update, :new, :create] do
    collection do
      get :searched
      get :viewed
      get :to_view
    end

    member do
      get :add_friend_book_reco
    end

    get 'books_search', to: "bookrecoms#books_search", as: :books_search
  end

  resources :podcastrecoms, only: [ :show, :index, :edit, :update, :new, :create] do
    collection do
      get :searched
      get :viewed
      get :to_view
    end

    member do
      get :add_friend_podcast_reco
    end

    get 'podcasts_search', to: "podcastrecoms#podcasts_search", as: :podcasts_search
  end

  resources :restaurantrecoms, only: [ :show, :index, :edit, :update, :new, :create] do
    collection do
      get :searched
      get :viewed
    end
    get 'restaurant_search', to: "restaurantrecoms#restaurants_search", as: :restaurants_search
  end

  resources :restaurants, only: [:show, :index, :edit, :update, :new, :create] do
    collection do
      get :searched
      get :viewed
    end
    member do
      get :add_friend_reco
    end
  end

  get "friend_show/:id", to: "users#friend_show", as: :friend_show
  # resources :users, only: :show
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  # validates :movie, uniqueness: true # >> plus de validation ici car pose problème avec l'ajout de films d'un ami
  # (ils ont le même ID). On contourne autrement.
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  def index
    reco_not_sorted = Recommendation.where(user_id: current_user.id)
    reco_sorted_asc = reco_not_sorted.sort_by {|reco| reco.created_at }
    @recommendations = reco_sorted_asc.reverse
  end

  def new
    @recommendation = Recommendation.new
    all_movies = Movie.all

    if params[:query].present? == false
      @movies = []
    else
      @movies = all_movies.where('title ILIKE ?', "%#{params[:query]}%")
    end

    respond_to do |format|
      format.html # Follow regular flow of Rails
      format.text { render partial: 'recommendations/movie_list', locals: { movies: @movies }, formats: [:html] }
    end
  end

  def create
    @recommendation = Recommendation.new(params_recommendations)
    @recommendation.user = current_user
    # trying to code différemment l'impossibilité de doublons :
    # @movie = Recommendation.where(user_id: current_user, movie_id: @recommendation.movie_id)
    # if @movie  != nil
    #   flash[:notice] = "Vous avez déja ce film dans votre liste"
    #   render :new
    # else
    #   @recommendation.save
    #   redirect_to recommendation_path(@recommendation)
    # end
    # code de départ :
    if @recommendation.save
      redirect_to recommendation_path(@recommendation)
    else
      @movies = Movie.where(id: @recommendation.movie_id)
      flash[:notice] = "Vous avez déja ce film dans votre liste"
      render :new
    end
  end

  def add_friend_reco
    friend_reco = Recommendation.find(params[:id])
    @recommendation = Recommendation.new
    @recommendation.user = current_user
    @recommendation.movie = friend_reco.movie
    friend_nickname = User.find(friend_reco.user_id).nickname
    @recommendation.comment = "Trouvé sur la liste de #{friend_nickname} avec ce commentaire : #{friend_reco.comment}"
    @recommendation.friend = friend_nickname
    if @recommendation.save
      redirect_to recommendations_path
    else
      render :new
    end
  end

  def show
    @recommendation = Recommendation.find(params[:id])
  end

  def edit
    @recommendation = Recommendation.find(params[:id])
  end

  def update
    @recommendation = Recommendation.find(params[:id])
    @recommendation.update(params_recommendations)
    redirect_to recommendation_path(@recommendation)
  end

  def searched
    reco_not_sorted = Recommendation.where(searched: true, user_id: current_user.id)
    reco_sorted_asc = reco_not_sorted.sort_by {|reco| reco.updated_at }
    @recommendations = reco_sorted_asc.reverse
  end

  def viewed
    reco_not_sorted = Recommendation.where(viewed: true, user_id: current_user.id )
    reco_sorted_asc = reco_not_sorted.sort_by {|reco| reco.updated_at }
    @recommendations = reco_sorted_asc.reverse
  end

  def to_view
    reco_not_sorted = Recommendation.where(viewed: false, user_id: current_user.id)
    reco_sorted_asc = reco_not_sorted.sort_by {|reco| reco.updated_at }
    @recommendations = reco_sorted_asc.reverse
  end

  def movies_search
    @recommendation = Recommendation.find(params[:recommendation_id])
    @recommendation.searched = true
    @recommendation.save
    moviename = @recommendation.movie.title.gsub(' ','+')
    redirect_to("https://www.google.fr/search?q=regarder+#{moviename}")
  end

  private

  def params_recommendations
    params.require(:recommendation).permit(:friend, :comment, :searched, :viewed,
                                           :feedback_content, :feedback_rating, :movie_id, :user_id)
  end
end

app/views/recommendations/_movie_list.html.erb
<div class="search-movie ps-3 py-3" data-search-movies-target="list">
  <% movies.each do |movie| %>
  <div data-controller="select-movies"        data-select-movies-target="choix"
        data-action="click->select-movies#save" data-value=<%= movie.id %>>
  <p id="movie"><%= movie.title %></p>
  </div>
    <% end %>
</div>

app/views/recommendations/edit.html.erb
<div class="container">
  <div>
    <%= simple_form_for @recommendation do |f| %>
      <%if @recommendation.viewed == false%>
        <%= f.input :friend %>
        <%= f.input :comment %>
      <% else%>
        <%= f.input :feedback_content, label: "Feedback" %>
        <%= f.input :feedback_rating, collection: (1..5).to_a, label: "Évaluer votre expérience" %>
      <% end %>
        <%= f.submit "Enregistrer", class: "btn-submit" %>
    <% end %>
  </div>
</div>

app/views/recommendations/index.html.erb
<div class="container">
  <div class="wrapper">
    <%@recommendations.select do |recommendation|%>
      <div class="movies-cards" style="max-width: 540px;">
        <%= link_to recommendation_path(recommendation), class:"text-decoration-none" do%>
          <div>
          <% if recommendation.movie.image_url.start_with?("http") %>
            <%= image_tag recommendation.movie.image_url, alt: "Poster", class: "img-fluid img-index" %>
          <% elsif recommendation.movie.image_url.start_with?("..//assets/images/") %>
            <%= image_tag recommendation.movie.image_url.gsub("..//assets/images/", ""), alt: "Poster", class: "img-fluid img-index" %>
          <% else %>
            <%= image_tag recommendation.movie.image_url.gsub("../assets/images/", ""), alt: "Poster", class: "img-fluid img-index" %>
          <% end %>
          </div>
            <%# <%= image_tag recommendation.movie.image_url, alt: "Poster", class: "img-fluid" %>
          <div>
            <h5 class="movies-card-header"><%=recommendation.movie.title %></h5>
          </div>
          <div>
          <% if recommendation.friend != nil %>
            <p class="movies-card-text"><i class="fa-solid fa-user"></i>  <%=recommendation.friend%></p>
          <% end %>
          </div>
        <%end %>
      </div>
    <%end%>
  </div>
</div>

app/views/recommendations/new.html.erb
<div class="container">
  <div data-controller="search-movies">
    <div class="search-target">
      <p style="color: red"><%= flash.notice %><p>
      <%= form_with url: new_recommendation_path, method: :get, html: { data: { search_movies_target: 'form' } } do |f| %>
        <%= f.text_field :query,
                        class: "form-control",
                        placeholder: 'Entrez un titre de film',
                        value: params[:query],
                        data: {
                            search_movies_target: 'input',
                            action: 'keyup->search-movies#update'
                          } %>
      <% end %>
      <%= render 'movie_list', movies: @movies %>
    </div>
    <div data-action="pick-movie@window->search-movies#createmovie form-reco">
      <%= simple_form_for @recommendation do |f| %>
      <%= f.input :movie_id, label: false, input_html: { class: "d-none", data: { search_movies_target: 'movie' }} %>
      <%= f.input :friend, label: "Ami" %>
      <%= f.input :comment, label: "Commentaire" %>
      <%= f.submit "Ajouter à ma liste", class: "btn-submit" %>
      <% end %>
    </div>
  </div>
  <%= render 'movie_list', movies: @movies %>
</div>

app/views/recommendations/searched.html.erb
<div class="container">
  <%@recommendations.select do |recommendation| if recommendation.viewed == false%>
  <div class="card shadow mb-5 bg-body" style="max-width: 540px;">
    <%= link_to recommendation_path(recommendation), class:"text-decoration-none" do%>
      <div class="cards g-0 d-flex">
        <div class="images-index">
        <% if recommendation.movie.image_url.start_with?("http") %>
          <%= image_tag recommendation.movie.image_url, alt: "Poster", class: "img-fluid img-index" %>
        <% elsif recommendation.movie.image_url.start_with?("..//assets/images/") %>
          <%= image_tag recommendation.movie.image_url.gsub("..//assets/images/", ""), alt: "Poster", class: "img-fluid img-index" %>
         <% else %>
           <%= image_tag recommendation.movie.image_url.gsub("../assets/images/", ""), alt: "Poster", class: "img-fluid img-index" %>
         <% end %>
          <%# <%= image_tag recommendation.movie.image_url, alt: "Poster", class: "img-fluid" %>
        </div>
        <div class="card-body card-body-index d-flex flex-column">
          <div>
            <h5 class="card-title"><%=recommendation.movie.title %></h5>
          </div>
          <div>
            <p class="card-text">Recommandé par: <%=recommendation.friend%></p>
          </div>
          <div>
            <p class="card-text">Ajouté le: <%=recommendation.created_at.strftime("%d/%m/%Y")%></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%end%>
  <%end%>
</div>

app/views/recommendations/show.html.erb
<%# <% content_for :meta_image, cl_image_path(@recommendation.image_url) %>
<% content_for :meta_title, "#{@recommendation.movie.title} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @recommendation.comment %>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8 col-lg-6">
      <div class="card card-show" style="width: 100%;">
        <% if @recommendation.movie.image_url.start_with?("http") %>
          <%= image_tag @recommendation.movie.image_url, alt: "Poster", class: "img" %>
        <% elsif @recommendation.movie.image_url.start_with?("..//assets/images/") %>
          <%= image_tag @recommendation.movie.image_url.gsub("..//assets/images/", ""), alt: "Poster", class: "img-fluid" %>
        <% else %>
          <%= image_tag @recommendation.movie.image_url.gsub("../assets/images/", ""), alt: "Poster", class: "img-fluid" %>
        <% end %>
        <h2><%= @recommendation.movie.title %></h2>
        <ul class="list-group list-group-flush">
          <li class="list-group-item"> <strong>Recommandé par :</strong> <%= @recommendation.friend.capitalize %></li>
          <li class="list-group-item"> <strong>Mon commentaire :</strong> <%= @recommendation.comment %>  <%= link_to edit_recommendation_path, class:"text-decoration-none link-modify ms-2" do %>
            <i class="fa-solid fa-pencil"></i>
          <% end %>
          </li>
          <li class="list-group-item"> <strong>Ajouté le :</strong> <%= @recommendation.created_at.strftime("%d/%m/%Y") %></li>
        </ul>
          <%= link_to "Regarder le film", recommendation_movies_search_path(@recommendation), class: "buttons button-watch text-decoration-none text-center" %>
        <div class="d-flex justify-content-around ms-3">
          <%= simple_form_for @recommendation, html: { class: "form-show" }, method: :patch  do |f| %>
            <%= f.input :viewed, label: 'Vu'  %>
            <%= f.submit "Sauvegarder", class: "buttons submit-button-form" %>
          <% end %>
          <% if @recommendation.viewed ==true && @recommendation.feedback_content == nil && @recommendation.feedback_rating == nil %>
          <%= link_to "Ajouter un feedback", edit_recommendation_path(@recommendation), class:"link-modify ms-3 mt-2" %>
          <% end %>
        </div>
        <div class="d-flex">
          <% if @recommendation.feedback_content != nil || @recommendation.feedback_rating != nil %>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
            <strong>Mon feedback :</strong>
            <% @recommendation.feedback_rating.times do %>
            <i class="fa-solid fa-star"></i>
            <% end %> <%= @recommendation.feedback_content %>
            <%= link_to edit_recommendation_path, class:"text-decoration-none link-modify ms-2" do %>
              <i class="fa-solid fa-pencil"></i>
            <% end %>
            </li>
          </ul>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/recommendations/to_view.html.erb
<div class="container">
  <div class="wrapper">
    <%@recommendations.select do |recommendation|%>
      <div class="movies-cards" style="max-width: 540px;">
        <%= link_to recommendation_path(recommendation), class:"text-decoration-none" do%>
          <div>
          <% if recommendation.movie.image_url.start_with?("http") %>
            <%= image_tag recommendation.movie.image_url, alt: "Poster", class: "img-fluid img-index" %>
          <% elsif recommendation.movie.image_url.start_with?("..//assets/images/") %>
            <%= image_tag recommendation.movie.image_url.gsub("..//assets/images/", ""), alt: "Poster", class: "img-fluid img-index" %>
          <% else %>
            <%= image_tag recommendation.movie.image_url.gsub("../assets/images/", ""), alt: "Poster", class: "img-fluid img-index" %>
          <% end %>
          </div>
            <%# <%= image_tag recommendation.movie.image_url, alt: "Poster", class: "img-fluid" %>
          <div>
            <h5 class="movies-card-header"><%=recommendation.movie.title %></h5>
          </div>
          <div>
          <% if recommendation.friend != nil %>
            <p class="movies-card-text"><i class="fa-solid fa-user"></i>  <%=recommendation.friend%></p>
          <% end %>
          </div>
        <%end %>
      </div>
    <%end%>
  </div>
</div>

app/views/recommendations/viewed.html.erb
<div class="container">
  <div class="wrapper">
    <%@recommendations.select do |recommendation|%>
      <div class="movies-cards" style="max-width: 540px;">
        <%= link_to recommendation_path(recommendation), class:"text-decoration-none" do%>
          <div>
          <% if recommendation.movie.image_url.start_with?("http") %>
            <%= image_tag recommendation.movie.image_url, alt: "Poster", class: "img-fluid img-index" %>
          <% elsif recommendation.movie.image_url.start_with?("..//assets/images/") %>
            <%= image_tag recommendation.movie.image_url.gsub("..//assets/images/", ""), alt: "Poster", class: "img-fluid img-index" %>
          <% else %>
            <%= image_tag recommendation.movie.image_url.gsub("../assets/images/", ""), alt: "Poster", class: "img-fluid img-index" %>
          <% end %>
          </div>
          <div>
            <% if recommendation.feedback_rating != nil %>
              <% recommendation.feedback_rating.times do %>
                <i class="fa-solid fa-star"></i>
              <% end %>
            <% end %>
          </div>
          <div>
            <h5 class="movies-card-header"><%=recommendation.movie.title %></h5>
          </div>
          <div>
          <% if recommendation.friend != nil %>
            <p class="movies-card-text"><i class="fa-solid fa-user"></i>  <%=recommendation.friend%></p>
          <% end %>
          </div>
        <%end %>
      </div>
    <%end%>
  </div>
</div>