config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :recommendations, only: [ :show, :index, :edit, :update, :new, :create] do
    collection do
      get :searched
      get :viewed
      get :to_view
    end

    member do
      get :add_friend_reco
    end

    get 'movies_search', to: "recommendations#movies_search", as: :movies_search
  end

  resources :bookrecoms, only: [ :show, :index, :edit, :update, :new, :create] do
    collection do
      get :searched
      get :viewed
      get :to_view
    end

    member do
      get :add_friend_book_reco
    end

    get 'books_search', to: "bookrecoms#books_search", as: :books_search
  end

  resources :podcastrecoms, only: [ :show, :index, :edit, :update, :new, :create] do
    collection do
      get :searched
      get :viewed
      get :to_view
    end

    member do
      get :add_friend_podcast_reco
    end

    get 'podcasts_search', to: "podcastrecoms#podcasts_search", as: :podcasts_search
  end

  resources :restaurantrecoms, only: [ :show, :index, :edit, :update, :new, :create] do
    collection do
      get :searched
      get :viewed
    end
    get 'restaurant_search', to: "restaurantrecoms#restaurants_search", as: :restaurants_search
  end

  resources :restaurants, only: [:show, :index, :edit, :update, :new, :create] do
    collection do
      get :searched
      get :viewed
    end
    member do
      get :add_friend_reco
    end
  end

  get "friend_show/:id", to: "users#friend_show", as: :friend_show
  # resources :users, only: :show
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recommendations
  has_many :bookrecoms
  # geocoded_by :ip_address,
  #             :latitude => :lat, :longitude => :lon
  # after_validation :geocode
  has_many :restaurantrecoms
  has_many :restaurants
  has_many :podcastrecoms
  # validates :nickname, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def friend_show
    @user = User.find(params[:id])
    user_recommendations = Recommendation.where(user_id: current_user.id)
    @user_friend = user_recommendations.map{ |reco|reco.friend }
    @user_friends = @user_friend.uniq
    # @friends = all_friends.uniq.reject! { |friend| User.where(nickname: friend).first == current_user }
    @movies = current_user.recommendations.map {|reco| reco.movie}
  end
end

app/views/users/_books_recommendations.html.erb
<div class="wrapper">
  <% if @user.bookrecoms == [] %>
    <p><%= @user.nickname %> n'a pas encore de livres dans sa liste.</p>
  <% else %>
    <%@user.bookrecoms.each do |bookrecom| %>
    <div class="movies-cards" style="max-width: 540px;">
      <div>
        <%= image_tag bookrecom.book.image_url, class: "img-fluid img-index" %>
      </div>
      <div>
        <% if bookrecom.feedback_rating != nil %>
          <% bookrecom.feedback_rating.times do %>
            <i class="fa-solid fa-star"></i>
          <% end %>
        <% end %>
      </div>
      <div>
        <h5 class="movies-card-header"><%=bookrecom.book.title %></h5>
      </div>
      <div class="card-profil my-4">
        <%= link_to "Ajouter à ma liste", add_friend_book_reco_bookrecom_path(bookrecom), class: 'buttons' %>
      </div>
    </div>
    <% end %>
  <% end %>
</div>

app/views/users/_movie_recommendations.html.erb
<div class="wrapper">
    <% @user.recommendations.each do |recommendation|%>
      <div class="movies-cards" style="max-width: 540px;">
        <%= link_to recommendation_path(recommendation), class:"text-decoration-none" do%>
          <div class="movies-image-card">
          <% if recommendation.movie.image_url.start_with?("http") %>
            <%= image_tag recommendation.movie.image_url, alt: "Poster", class: "img-fluid img-index" %>
          <% elsif recommendation.movie.image_url.start_with?("..//assets/images/") %>
            <%= image_tag recommendation.movie.image_url.gsub("..//assets/images/", ""), alt: "Poster", class: "img-fluid img-index" %>
          <% else %>
            <%= image_tag recommendation.movie.image_url.gsub("../assets/images/", ""), alt: "Poster", class: "img-fluid img-index" %>
          <% end %>
          </div>
            <%# <%= image_tag recommendation.movie.image_url, alt: "Poster", class: "img-fluid" %>
          <div>
            <h5 class="card-title"><%=recommendation.movie.title %></h5>
          </div>
          <div>
            <p class="card-text">Recommandé par: <%=recommendation.friend%></p>
          </div>
          <div>
            <p class="card-text">Ajouté le: <%=recommendation.created_at.strftime("%d/%m/%Y")%></p>
          </div>
        <%end %>
      </div>
    <%end%>
  </div>

app/views/users/_movies_recommendations.html.erb
<div class="wrapper">
  <% if @user.recommendations == [] %>
    <p><%= @user.nickname %> n'a pas encore de films dans sa liste.</p>
  <% else %>
    <% @user.recommendations.each do |recommendation|%>
      <div class="movies-cards" style="max-width: 540px;">
        <div>
          <% if recommendation.movie.image_url.start_with?("http") %>
            <%= image_tag recommendation.movie.image_url, alt: "Poster", class: "img-fluid img-index" %>
          <% elsif recommendation.movie.image_url.start_with?("..//assets/images/") %>
            <%= image_tag recommendation.movie.image_url.gsub("..//assets/images/", ""), alt: "Poster", class: "img-fluid img-index" %>
          <% else %>
            <%= image_tag recommendation.movie.image_url.gsub("../assets/images/", ""), alt: "Poster", class: "img-fluid img-index" %>
          <% end %>
        </div>
        <div>
        <% if recommendation.feedback_rating != nil %>
          <% recommendation.feedback_rating.times do %>
            <i class="fa-solid fa-star"></i>
          <% end %>
        <% end %>
      </div>
        <div>
          <h5 class="movies-card-header"><%=recommendation.movie.title %></h5>
        </div>
        <% if @movies.include?(recommendation.movie) == true %>
          <p>Ce film fait déjà partie de votre liste.</p>
        <% else %>
          <div class="card-profil my-4">
            <%= link_to "Ajouter à ma liste", add_friend_reco_recommendation_path(recommendation), class: 'buttons' %>
          </div>
        <% end %>
      </div>
    <%end%>
  <% end %>
</div>

app/views/users/_podcasts_recommendations.html.erb
<div class="wrapper">
  <% if @user.podcastrecoms == [] %>
    <p><%= @user.nickname %> n'a pas encore de podcasts dans sa liste.</p>
  <% else %>
    <%@user.podcastrecoms.each do |podcastrecom| %>
      <div class="movies-cards" style="max-width: 540px;">
        <div>
          <%= image_tag podcastrecom.podcast.image_url, class: "img-fluid img-index" %>
        </div>
        <div>
        <% if podcastrecom.feedback_rating != nil %>
          <% podcastrecom.feedback_rating.times do %>
            <i class="fa-solid fa-star"></i>
          <% end %>
        <% end %>
      </div>
        <div>
          <h5 class="movies-card-header"> <%= podcastrecom.podcast.title %> </h5>
        </div>
        <div class="card-profil my-4">
          <%= link_to "Ajouter à ma liste", add_friend_podcast_reco_podcastrecom_path(podcastrecom), class: 'buttons' %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/_restaurants_recommendations.html.erb
<div class="wrapper">
  <% if @user.restaurants == [] %>
    <p><%= @user.nickname %> n'a pas encore de restaurants dans sa liste.</p>
  <% else %>
    <%@user.restaurants.each do |restaurant| %>
    <div class="movies-cards" style="max-width: 540px;">
      <%= link_to restaurant_path(restaurant), class:"text-decoration-none" do%>
        <div>
          <%#= image_tag restaurantrecoms.restaurant.image_url, class: "img-fluid img-index" %>
        </div>
        <div>
          <h5 class="movies-card-header"><%=restaurant.title %></h5>
        </div>
        <div class="card-profil my-4">
          <%= link_to "Ajouter à ma liste", add_friend_reco_restaurant_path(restaurant), class: 'buttons' %>
        </div>
      <%end%>
    </div>
    <%end%>
  <% end %>
</div>

app/views/users/friend_show.html.erb
<div class="container">
  <div class="col-12 col-md-6">
    <div class="card card-show" style="width: 100%;">
      <% if current_user.id == params[:id].to_i %>
        <h1>Salut <%= current_user.nickname.capitalize %> !</h1>
        <h2>Mes listes :</h2>
        <% if @recommendations == [] && @bookrecoms == [] && @podcastrecoms == [] && @restaurants == [] %>
          <p>Vous n'avez pas encore de listes !</p>
        <% end %>
        <ul class="list-group list-group-flush ms-2">
          <li class="list-group-item"><%= link_to "Mes films", recommendations_path, class:" link-modify"%></li>
          <li class="list-group-item"><%= link_to "Mes livres", bookrecoms_path, class:" link-modify" %></li>
          <li class="list-group-item"><%= link_to "Mes podcasts", podcastrecoms_path, class:" link-modify" %></li>
          <li class="list-group-item"><%= link_to "Mes restos", restaurantrecoms_path, class:" link-modify" %></li>
        </ul>
        <h2>Mes amis :</h2>
        <% if @friends == [] %>
          <p>Vous n'avez pas encore d'amis !</p>
        <% end %>
        <ul class="list-group list-group-flush">
          <% @user_friends.each do |friend| %>
          <% friend_user = User.where(nickname: friend).first %>
            <% if friend_user != nil %>
              <%= link_to friend_show_path(friend_user), class:" link-modify ms-2" do %>
                <li class="list-group-item list-link-friend"> <%= friend_user.nickname.capitalize %></li>
              <% end %>
            <% else %>
              <li class="list-group-item ms-2"><%= Recommendation.where(friend: friend).first.friend.capitalize %> (l'ami n'a pas l'app)</li>
            <% end %>
          <% end %>
        </ul>
      <% else %>
          <h2>Les listes de <%= @user.nickname.capitalize %> :</h2>
        <div class="py-2">
          <ul class="nav nav-tabs py-2" id="myTab" role="tablist">
            <li class="nav-item" role="presentation">
              <button class="nav-link buttons rounded active" id="films-tab" data-bs-toggle="tab" data-bs-target="#films" type="button" role="tab" aria-controls="films" aria-selected="true">Films</button>
            </li>
            <li class="nav-item" role="presentation">
              <button class="nav-link buttons rounded" id="livres-tab" data-bs-toggle="tab" data-bs-target="#livres" type="button" role="tab" aria-controls="livres" aria-selected="false">Livres</button>
            </li>
            <li class="nav-item" role="presentation">
              <button class="nav-link buttons rounded" id="podcasts-tab" data-bs-toggle="tab" data-bs-target="#podcasts" type="button" role="tab" aria-controls="podcasts" aria-selected="false">Podcasts</button>
            </li>
            <li class="nav-item" role="presentation">
            <button class="nav-link buttons rounded" id="restaurants-tab" data-bs-toggle="tab" data-bs-target="#restaurants" type="button" role="tab" aria-controls="restaurants" aria-selected="false">Restaurants</button>
            </li>
          </ul>
        </div>
        <div class="tab-content" id="myTabContent">
          <div class="tab-pane fade show active" id="films" role="tabpanel" aria-labelledby="films-tab">
            <%= render 'movies_recommendations' %>
          </div>
          <div class="tab-pane fade" id="livres" role="tabpanel" aria-labelledby="livres-tab">
            <%= render 'books_recommendations' %>
          </div>
          <div class="tab-pane fade" id="podcasts" role="tabpanel" aria-labelledby="podcasts-tab">
            <%= render 'podcasts_recommendations' %>
          </div>
          <div class="tab-pane fade" id="restaurants" role="tabpanel" aria-labelledby="restaurants-tab">
            <%= render 'restaurants_recommendations' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="col-12 col-md-6">
    <div class="card card-show" style="width: 100%;">
      <% if current_user.id == params[:id].to_i %>
        <h1>Salut <%= current_user.nickname.capitalize %> !</h1>
        <h2>Mes listes :</h2>
        <% if @recommendations == [] && @bookrecoms == [] && @podcastrecoms == [] && @restaurantrecoms == [] %>
          <p>Vous n'avez pas encore de listes !</p>
        <% end %>
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><%= link_to "Mes films", recommendations_path, class:"text-decoration-none link-modify"%></li>
          <li class="list-group-item"><%= link_to "Mes livres", bookrecoms_path, class:"text-decoration-none link-modify" %></li>
          <li class="list-group-item"><%= link_to "Mes podcasts", podcastrecoms_path, class:"text-decoration-none link-modify" %></li>
          <li class="list-group-item"><%= link_to "Mes restos", restaurantrecoms_path, class:"text-decoration-none link-modify" %></li>
        </ul>
        <h2>Mes amis :</h2>
        <% if @friends == [] %>
          <p>Vous n'avez pas encore d'amis !</p>
        <% end %>
        <ul class="list-group list-group-flush">
          <% @user_friends.each do |friend| %>
          <% friend_user = User.where(nickname: friend).first %>
            <% if friend_user != nil %>
            <li class="list-group-item"> <%= friend_user.nickname.capitalize %> <%= link_to "- Voir profil -", user_path(friend_user), class:"text-decoration-none link-modify ms-2" %> </li>
            <% else %>
            <li class="list-group-item"> <%= Recommendation.where(friend: friend).first.friend %> (l'ami n'a pas l'app)</li>
            <% end %>
          <% end %>
        </ul>
      <% else %>
          <h2>Les listes de <%= @user.nickname %> :</h2>
        <div class="py-2">
          <ul class="nav nav-tabs py-2" id="myTab" role="tablist">
            <li class="nav-item" role="presentation">
              <button class="nav-link buttons rounded active" id="films-tab" data-bs-toggle="tab" data-bs-target="#films" type="button" role="tab" aria-controls="films" aria-selected="true">Films</button>
            </li>
            <li class="nav-item" role="presentation">
              <button class="nav-link buttons rounded" id="livres-tab" data-bs-toggle="tab" data-bs-target="#livres" type="button" role="tab" aria-controls="livres" aria-selected="false">Livres</button>
            </li>
            <li class="nav-item" role="presentation">
              <button class="nav-link buttons rounded" id="podcasts-tab" data-bs-toggle="tab" data-bs-target="#podcasts" type="button" role="tab" aria-controls="podcasts" aria-selected="false">Podcasts</button>
            </li>
            <li class="nav-item" role="presentation">
            <button class="nav-link buttons rounded" id="restaurants-tab" data-bs-toggle="tab" data-bs-target="#restaurants" type="button" role="tab" aria-controls="restaurants" aria-selected="false">Restaurants</button>
            </li>
          </ul>
        </div>
        <div class="tab-content" id="myTabContent">
          <div class="tab-pane fade show active" id="films" role="tabpanel" aria-labelledby="films-tab">
            <%= render 'movies_recommendations' %>
          </div>
          <div class="tab-pane fade" id="livres" role="tabpanel" aria-labelledby="livres-tab">
            <%= render 'books_recommendations' %>
          </div>
          <div class="tab-pane fade" id="podcasts" role="tabpanel" aria-labelledby="podcasts-tab">
            <%= render 'podcasts_recommendations' %>
          </div>
          <div class="tab-pane fade" id="restaurants" role="tabpanel" aria-labelledby="restaurants-tab">
            <%= render 'restaurants_recommendations' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>