config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :recommendations, only: [ :show, :index, :edit, :update, :new, :create] do
    collection do
      get :searched
      get :viewed
      get :to_view
    end

    member do
      get :add_friend_reco
    end

    get 'movies_search', to: "recommendations#movies_search", as: :movies_search
  end

  resources :bookrecoms, only: [ :show, :index, :edit, :update, :new, :create] do
    collection do
      get :searched
      get :viewed
      get :to_view
    end

    member do
      get :add_friend_book_reco
    end

    get 'books_search', to: "bookrecoms#books_search", as: :books_search
  end

  resources :podcastrecoms, only: [ :show, :index, :edit, :update, :new, :create] do
    collection do
      get :searched
      get :viewed
      get :to_view
    end

    member do
      get :add_friend_podcast_reco
    end

    get 'podcasts_search', to: "podcastrecoms#podcasts_search", as: :podcasts_search
  end

  resources :restaurantrecoms, only: [ :show, :index, :edit, :update, :new, :create] do
    collection do
      get :searched
      get :viewed
    end
    get 'restaurant_search', to: "restaurantrecoms#restaurants_search", as: :restaurants_search
  end

  resources :restaurants, only: [:show, :index, :edit, :update, :new, :create] do
    collection do
      get :searched
      get :viewed
    end
    member do
      get :add_friend_reco
    end
  end

  get "friend_show/:id", to: "users#friend_show", as: :friend_show
  # resources :users, only: :show
end

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.6),rgba(16,16,16,1)), url(assets/home3.jpg);" >
  <div class="container">
    <div class="">
      <h1>NUTS</h1>
      <p><span data-controller="typed-js"></span></p>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<!-- app/views/shared/_ios_pwa_links.html.erb -->
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar sticky-top d-flex justify-content-between align-items-center px-1">
  <!-- changes header on sites --->
  <%= image_tag 'nuts-logo-red2.png', class: "img-navbar me-auto" %>

  <!-- button home --->
  <!-- dropdown menus --->
  <% if user_signed_in? %>
    <div class="dropdown">
      <i class="fa-solid fa-user text-decoration-none button-navigation mx-1 py-3"></i>
      <div class="dropdown-content">
        <%= link_to 'Mon profil',friend_show_path(current_user), class:"text-decoration-none button-navigation mx-1" %>
        <%= link_to 'Log out', destroy_user_session_path, method: :delete, class:"text-decoration-none button-navigation mx-1" %>
      </div>
    </div>
  <% else %>
    <%= link_to new_user_session_path, class:"text-decoration-none button-navigation mx-1" do %>
      <i class="fa-solid fa-user py-2"></i>
    <% end %>
  <% end %>
  <div class="dropdown">
    <i class="fas fa-plus text-decoration-none button-navigation mx-1 py-3"></i>
    <div class="dropdown-content">
      <%= link_to 'Film', new_recommendation_path, class:"text-decoration-none button-navigation mx-1" %>
      <%= link_to 'Livre', new_bookrecom_path, class:"text-decoration-none button-navigation mx-1" %>
      <%= link_to 'Podcast', new_podcastrecom_path, class:"text-decoration-none button-navigation mx-1" %>
      <%= link_to 'Restaurant', new_restaurant_path, class:"text-decoration-none button-navigation mx-1" %>
    </div>
  </div>
</div>

app/views/shared/_navbar_pages.html.erb
<div class="navbar-index sticky-top d-flex justify-content-between align-items-center px-1">
  <!-- condition to come back always to index page when in show --->
  <% if params[:controller] == 'recommendations' && params[:action] == 'show' %>
    <%= link_to recommendations_path, class:"text-decoration-none button-navigation me-1" do %>
      <i class="fas fa-arrow-left"></i>
    <% end %>
  <% else %>
    <%= link_to :back, class:"text-decoration-none button-navigation me-1" do %>
      <i class="fas fa-arrow-left"></i>
    <% end %>
  <% end %>
  <!-- changes header on sites --->
  <% if params[:controller] == 'recommendations' && params[:action] == 'index' %>
    <h2 class="titre-index me-auto m-0 mx-1">Tous mes films</h2>
  <% elsif params[:controller] == 'recommendations' && params[:action] == 'show' %>
    <h2 class="titre-index me-auto m-0 mx-1">Détails du film</h2>
  <% elsif params[:controller] == 'recommendations' && params[:action] == 'viewed' %>
    <h2 class="titre-index me-auto m-0 mx-1">Films vus</h2>
  <% elsif params[:controller] == 'recommendations' && params[:action] == 'searched' %>
    <h2 class="titre-index me-auto m-0 mx-1">Recherchés</h2>
  <% elsif params[:controller] == 'recommendations' && params[:action] == 'to_view' %>
    <h2 class="titre-index me-auto m-0 mx-1">Films à voir</h2>
  <% elsif params[:controller] == 'recommendations' && params[:action] == 'edit' %>
    <h2 class="titre-index me-auto m-0 mx-1">Modifier</h2>
  <% elsif params[:controller] == 'users' && params[:action] == 'show' %>
    <h2 class="titre-index me-auto m-0 mx-1">Profil</h2>
  <% elsif params[:controller] == 'podcastrecoms' && params[:action] == 'index' %>
    <h2 class="titre-index me-auto m-0 mx-1">Tous mes podcasts</h2>
  <% elsif params[:controller] == 'podcastrecoms' && params[:action] == 'show' %>
    <h2 class="titre-index me-auto m-0 mx-1">Détails du podcast</h2>
  <% elsif params[:controller] == 'podcastrecoms' && params[:action] == 'viewed' %>
    <h2 class="titre-index me-auto m-0 mx-1">Podcasts écoutés</h2>
  <% elsif params[:controller] == 'podcastrecoms' && params[:action] == 'edit' %>
    <h2 class="titre-index me-auto m-0 mx-1">Modifier</h2>
  <% elsif params[:controller] == 'bookrecoms' && params[:action] == 'index' %>
    <h2 class="titre-index me-auto m-0 mx-1">Tous mes livres</h2>
  <% elsif params[:controller] == 'bookrecoms' && params[:action] == 'show' %>
    <h2 class="titre-index me-auto m-0 mx-1">Détails du livre</h2>
  <% elsif params[:controller] == 'bookrecoms' && params[:action] == 'viewed' %>
    <h2 class="titre-index me-auto m-0 mx-1">Livres lus</h2>
  <% elsif params[:controller] == 'bookrecoms' && params[:action] == 'edit' %>
    <h2 class="titre-index me-auto m-0 mx-1">Modifier</h2>
  <% elsif params[:controller] == 'restaurants' && params[:action] == 'index' %>
    <h2 class="titre-index me-auto m-0 mx-1">Tous mes restos</h2>
  <% elsif params[:controller] == 'restaurants' && params[:action] == 'show' %>
    <h2 class="titre-index me-auto m-0 mx-1">Détails du resto</h2>
  <% elsif params[:controller] == 'restaurants' && params[:action] == 'viewed' %>
    <h2 class="titre-index me-auto m-0 mx-1">Restos visités</h2>
  <% elsif params[:controller] == 'restaurants' && params[:action] == 'edit' %>
    <h2 class="titre-index me-auto m-0 mx-1">Modifier</h2>
  <% end %>
  <!-- button home --->
  <%= link_to root_path, class:"text-decoration-none button-navigation mx-1" do %>
    <i class="fas fa-home py-2"></i>
  <% end %>
  <!-- dropdown menus --->
  <% if user_signed_in? %>
    <div class="dropdown">
      <i class="fa-solid fa-user text-decoration-none button-navigation mx-1 py-3"></i>
      <div class="dropdown-content">
        <%= link_to 'Mon profil',friend_show_path(current_user), class:"text-decoration-none button-navigation mx-1" %>
        <%= link_to 'Log out', destroy_user_session_path, method: :delete, class:"text-decoration-none button-navigation mx-1" %>
      </div>
    </div>
  <% else %>
    <%= link_to new_user_session_path, class:"text-decoration-none button-navigation mx-1" do %>
      <i class="fa-solid fa-user py-2"></i>
    <% end %>
  <% end %>
  <div class="dropdown">
    <i class="fa-solid fa-eye text-decoration-none button-navigation mx-1 py-3"></i>
    <div class="dropdown-content">
    <% if params[:controller] == 'recommendations'%>
      <%= link_to 'À voir', to_view_recommendations_path, class:"text-decoration-none button-navigation mx-1" %>
      <%= link_to 'Film vus', viewed_recommendations_path, class:"text-decoration-none button-navigation mx-1" %>
      <%= link_to 'Tous mes films', recommendations_path, class:"text-decoration-none button-navigation mx-1" %>
    <% elsif params[:controller] == 'podcastrecoms'%>
      <%= link_to 'Podcast à écouter', to_view_podcastrecoms_path, class:"text-decoration-none button-navigation mx-1" %>
      <%= link_to 'Podcast écoutés', viewed_podcastrecoms_path, class:"text-decoration-none button-navigation mx-1" %>
      <%= link_to 'Tous mes podcasts', podcastrecoms_path, class:"text-decoration-none button-navigation mx-1" %>
    <% elsif params[:controller] == 'bookrecoms'%>
      <%= link_to 'À lire', to_view_bookrecoms_path, class:"text-decoration-none button-navigation mx-1" %>
      <%= link_to 'Livres lus', viewed_bookrecoms_path, class:"text-decoration-none button-navigation mx-1" %>
      <%= link_to 'Tous mes livres', bookrecoms_path, class:"text-decoration-none button-navigation mx-1" %>
    <% elsif params[:controller] == 'restaurants'%>
      <%= link_to 'Restos visités', viewed_restaurants_path, class:"text-decoration-none button-navigation mx-1" %>
      <%= link_to 'Tous mes restos', restaurants_path, class:"text-decoration-none button-navigation mx-1" %>
    <% elsif params[:controller] == 'users'%>
      <%= link_to 'Mes films', recommendations_path, class:"text-decoration-none button-navigation mx-1" %>
      <%= link_to 'Mes livres', bookrecoms_path, class:"text-decoration-none button-navigation mx-1" %>
      <%= link_to 'Mes podcasts', podcastrecoms_path, class:"text-decoration-none button-navigation mx-1" %>
      <%= link_to 'Mes restos', restaurantrecoms_path, class:"text-decoration-none button-navigation mx-1" %>
    <%end%>
    </div>
  </div>
  <div class="dropdown">
    <i class="fas fa-plus text-decoration-none button-navigation mx-1 py-3"></i>
    <div class="dropdown-content">
      <%= link_to 'Film', new_recommendation_path, class:"text-decoration-none button-navigation mx-1" %>
      <%= link_to 'Livre', new_bookrecom_path, class:"text-decoration-none button-navigation mx-1" %>
      <%= link_to 'Podcast', new_podcastrecom_path, class:"text-decoration-none button-navigation mx-1" %>
      <%= link_to 'Restaurant', new_restaurant_path, class:"text-decoration-none button-navigation mx-1" %>
    </div>
  </div>
</div>