config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :recommendations, only: [ :show, :index, :edit, :update, :new, :create] do
    collection do
      get :searched
      get :viewed
      get :to_view
    end

    member do
      get :add_friend_reco
    end

    get 'movies_search', to: "recommendations#movies_search", as: :movies_search
  end

  resources :bookrecoms, only: [ :show, :index, :edit, :update, :new, :create] do
    collection do
      get :searched
      get :viewed
      get :to_view
    end

    member do
      get :add_friend_book_reco
    end

    get 'books_search', to: "bookrecoms#books_search", as: :books_search
  end

  resources :podcastrecoms, only: [ :show, :index, :edit, :update, :new, :create] do
    collection do
      get :searched
      get :viewed
      get :to_view
    end

    member do
      get :add_friend_podcast_reco
    end

    get 'podcasts_search', to: "podcastrecoms#podcasts_search", as: :podcasts_search
  end

  resources :restaurantrecoms, only: [ :show, :index, :edit, :update, :new, :create] do
    collection do
      get :searched
      get :viewed
    end
    get 'restaurant_search', to: "restaurantrecoms#restaurants_search", as: :restaurants_search
  end

  resources :restaurants, only: [:show, :index, :edit, :update, :new, :create] do
    collection do
      get :searched
      get :viewed
    end
    member do
      get :add_friend_reco
    end
  end

  get "friend_show/:id", to: "users#friend_show", as: :friend_show
  # resources :users, only: :show
end

app/models/podcastrecom.rb
class Podcastrecom < ApplicationRecord
  belongs_to :user
  belongs_to :podcast
end

app/controllers/podcastrecoms_controller.rb
class PodcastrecomsController < ApplicationController
  def index
    reco_not_sorted = Podcastrecom.where(user_id: current_user.id)
    reco_sorted_asc = reco_not_sorted.sort_by {|reco| reco.created_at }
    @podcastrecoms = reco_sorted_asc.reverse
  end

  def new
    @podcastrecom = Podcastrecom.new
    all_podcasts = Podcast.all

    if params[:query].present? == false
      @podcasts = []
    else
      @podcasts = all_podcasts.where('title ILIKE ?', "%#{params[:query]}%")
    end

    respond_to do |format|
      format.html # Follow regular flow of Rails
      format.text { render partial: 'podcastrecoms/podcast_list', locals: { podcasts: @podcasts }, formats: [:html] }
    end
  end

  def create
    @podcastrecom = Podcastrecom.new(params_podcastrecoms)
    @podcastrecom.user = current_user
    if @podcastrecom.save
      redirect_to podcastrecom_path(@podcastrecom)
    else
      render :new
    end
  end

  def add_friend_podcast_reco
    friend_reco = Podcastrecom.find(params[:id])
    @recommendation = Podcastrecom.new
    @recommendation.user = current_user
    @recommendation.podcast = friend_reco.podcast
    friend_nickname = User.find(friend_reco.user_id).nickname
    @recommendation.comment = "Trouvé sur la liste de #{friend_nickname} avec ce commentaire : #{friend_reco.comment}"
    @recommendation.friend = friend_nickname
    if @recommendation.save
      redirect_to podcastrecoms_path
    else
      render :new
    end
  end

  def show
    @podcastrecom = Podcastrecom.find(params[:id])
  end

  def edit
    @podcastrecom = Podcastrecom.find(params[:id])
  end

  def update
    @podcastrecom = Podcastrecom.find(params[:id])
    @podcastrecom.update(params_podcastrecoms)
    redirect_to podcastrecom_path(@podcastrecom)
  end

  def searched
    reco_not_sorted = Podcastrecom.where(searched: true, user_id: current_user.id)
    reco_sorted_asc = reco_not_sorted.sort_by {|reco| reco.updated_at }
    @podcastrecoms = reco_sorted_asc.reverse
  end

  def viewed
    reco_not_sorted = Podcastrecom.where(viewed: true, user_id: current_user.id )
    reco_sorted_asc = reco_not_sorted.sort_by {|reco| reco.updated_at }
    @podcastrecoms = reco_sorted_asc.reverse
  end

  def to_view
    reco_not_sorted = Podcastrecom.where(viewed: false, user_id: current_user.id)
    reco_sorted_asc = reco_not_sorted.sort_by {|reco| reco.updated_at }
    @podcastrecoms = reco_sorted_asc.reverse
  end

  def podcasts_search
    @podcastrecom = Podcastrecom.find(params[:podcastrecom_id])
    @podcastrecom.searched = true
    @podcastrecom.save
    podcastname = @podcastrecom.podcast.title.gsub(' ','+')
    redirect_to("https://www.google.fr/search?q=ecouter+des+podcasts+#{podcastname}")
  end

  private

  def params_podcastrecoms
    params.require(:podcastrecom).permit(:friend, :comment, :searched, :viewed,
                                         :feedback_content, :feedback_rating, :podcast_id, :user_id)
  end
end

app/views/podcastrecoms/_podcast_list.html.erb
<div class="search-podcast ps-3 py-3 search-bar-text" data-search-podcasts-target="list">
  <% podcasts.each do |podcast| %>
  <div data-controller="select-podcasts"        data-select-podcasts-target="choix"
        data-action="click->select-podcasts#save" data-value=<%= podcast.id %>>
  <p id="podcast"><%= podcast.title %></p>
  </div>
    <% end %>
</div>

app/views/podcastrecoms/edit.html.erb
<div class="container">
  <div>
    <%= simple_form_for @podcastrecom do |f| %>
      <%if @podcastrecom.viewed == false%>
        <%= f.input :friend %>
        <%= f.input :comment %>
      <% else%>
        <%= f.input :feedback_content, label: "Feedback" %>
        <%= f.input :feedback_rating, collection: (1..5).to_a, label: "Évaluer votre expérience" %>
      <% end %>
        <%= f.submit "Enregistrer", class: "btn-submit" %>
    <% end %>
  </div>
</div>

app/views/podcastrecoms/index.html.erb
<div class="container">
  <div class="wrapper">
    <%@podcastrecoms.select do |podcastrecom|%>
      <div class="movies-cards" style="max-width: 540px;">
        <%= link_to podcastrecom_path(podcastrecom), class:"text-decoration-none" do%>
          <div>
          <% if podcastrecom.podcast.image_url.start_with?("http") %>
            <%= image_tag podcastrecom.podcats.image_url, alt: "Poster", class: "img-fluid img-index" %>
          <% elsif podcastrecom.podcast.image_url.start_with?("..//assets/images/") %>
            <%= image_tag podcastrecom.podcast.image_url.gsub("..//assets/images/", ""), alt: "Poster", class: "img-fluid img-index" %>
          <% else %>
            <%= image_tag podcastrecom.podcast.image_url.gsub("../assets/images/", ""), alt: "Poster", class: "img-fluid img-index" %>
          <% end %>
          </div>
            <%# <%= image_tag podcastrecom.podcast.image_url, alt: "Poster", class: "img-fluid" %>
          <div>
            <h5 class="movies-card-text movies-card-header"><%=podcastrecom.podcast.title %></h5>
          </div>
          <div>
          <% if podcastrecom.friend != nil %>
            <p class="movies-card-text"><i class="fa-solid fa-user"></i>  <%=podcastrecom.friend%></p>
          <% end %>
          </div>
        <%end %>
      </div>
    <%end%>
  </div>
</div>

app/views/podcastrecoms/new.html.erb
<div class="container">
  <div data-controller="search-podcasts">
    <div class="search-target">
      <%= form_with url: new_podcastrecom_path, method: :get, html: { data: { search_podcasts_target: 'form' } } do |f| %>
        <%= f.text_field :query,
                        class: "form-control",
                        placeholder: 'Entrez un titre de podcast',
                        value: params[:query],
                        data: {
                            search_podcasts_target: 'input',
                            action: 'keyup->search-podcasts#update'
                          } %>
      <% end %>
      <%= render 'podcast_list', podcasts: @podcasts %>
    </div>
    <div data-action="pick-podcast@window->search-podcasts#createpodcast form-reco">
      <%= simple_form_for @podcastrecom do |f| %>
      <%= f.input :podcast_id, label: false, input_html: { class: "d-none", data: { search_podcasts_target: 'podcast' }} %>
      <%= f.input :friend, label: "Ami" %>
      <%= f.input :comment, label: "Commentaire" %>
      <%= f.submit "Ajouter à ma list", class: "btn-submit" %>
      <% end %>
    </div>
  </div>
  <div class="my-4">
  </div>
  <%= render 'podcast_list', podcasts: @podcasts %>
</div>

app/views/podcastrecoms/searched.html.erb
<div class="container">
  <h1>Podcasts récemment recherchés</h1>
  <%@podcastrecoms.each do |podcastrecom|%>
  <div class="card shadow mb-5 bg-body" style="max-width: 540px;">
    <%= link_to podcastrecom_path(podcastrecom), class:"text-decoration-none" do%>
      <div class="cards g-0 d-flex">
        <div class="card-body d-flex flex-column">
          <div>
            <h5 class="card-title"><%=podcastrecom.podcast.title %></h5>
          </div>
          <div>
            <p class="card-text">Recommandé par: <%=podcastrecom.friend%></p>
          </div>
          <div>
            <p class="card-text">Recherché le: <%=podcastrecom.updated_at.strftime("%m/%d/%Y")%></p>
          </div>
          <div>
            <%= simple_form_for podcastrecom do |f| %>
              <%= f.input :viewed, label: 'vu?' %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%end%>
  <div class="d-flex justify-content-around">
    <div>
      <%= link_to "Ajouter un podcast", new_podcastrecom_path, class:"text-decoration-none buttons" %>
    </div>
    <div>
      <%= link_to "Retour", root_path, class:"text-decoration-none buttons" %>
    </div>
  </div>
</div>

app/views/podcastrecoms/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8 col-lg-6">
      <div class="card card-show" style="width: 100%;">
        <% if @podcastrecom.podcast.image_url.start_with?("http") %>
          <%= image_tag @podcastrecom.podcast.image_url, alt: "Poster", class: "img-fluid"  %>
        <% elsif @podcastrecom.podcast.image_url.start_with?("..//assets/images/") %>
          <%= image_tag @podcastrecom.podcast.image_url.gsub("..//assets/images/", ""), alt: "Poster", class: "img-fluid" %>
        <% else %>
          <%= image_tag @podcastrecom.podcast.image_url.gsub("../assets/images/", ""), alt: "Poster", class: "img-fluid" %>
        <% end %>
        <h2><%= @podcastrecom.podcast.title %></h2>
        <ul class="list-group list-group-flush">
          <li class="list-group-item"> <strong>Recommandé par :</strong> <%= @podcastrecom.friend.capitalize %></li>
          <li class="list-group-item"> <strong>Mon commentaire :</strong> <%= @podcastrecom.comment %>  <%= link_to edit_podcastrecom_path, class:"text-decoration-none link-modify ms-2" do %>
            <i class="fa-solid fa-pencil"></i>
          <% end %>
          </li>
          <li class="list-group-item"> <strong>Ajouté le :</strong> <%= @podcastrecom.created_at.strftime("%d/%m/%Y") %></li>
        </ul>
          <%= link_to "Écouter le podcast", podcastrecom_podcasts_search_path(@podcastrecom), class: "buttons button-watch text-decoration-none text-center" %>
        <div class="d-flex justify-content-around ms-3">
          <%= simple_form_for @podcastrecom, html: { class: "form-show" }, method: :patch  do |f| %>
            <%= f.input :viewed, label: 'Écouté'  %>
            <%= f.submit "Sauvegarder", class: "buttons submit-button-form" %>
          <% end %>
          <% if @podcastrecom.viewed ==true && @podcastrecom.feedback_content == nil && @podcastrecom.feedback_rating == nil %>
          <%= link_to "Ajouter un feedback", edit_podcastrecom_path(@podcastrecom), class:"text-decoration-none link-modify ms-3 mt-2" %>
          <% end %>
        </div>
        <div class="d-flex">
          <% if @podcastrecom.feedback_content != nil || @podcastrecom.feedback_rating != nil %>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
            <strong>Mon feedback :</strong>
            <% @podcastrecom.feedback_rating.times do %>
            <i class="fa-solid fa-star"></i>
            <% end %> <%= @podcastrecom.feedback_content %>
            <%= link_to edit_podcastrecom_path, class:"text-decoration-none link-modify ms-2" do %>
              <i class="fa-solid fa-pencil"></i>
            <% end %>

            </li>
          </ul>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/podcastrecoms/to_view.html.erb
<div class="container">
  <div class="wrapper">
    <%@podcastrecoms.select do |recommendation|%>
      <div class="movies-cards" style="max-width: 540px;">
        <%= link_to podcastrecom_path(recommendation), class:"text-decoration-none" do%>
          <div>
          <% if recommendation.podcast.image_url.start_with?("http") %>
            <%= image_tag recommendation.podcast.image_url, alt: "Poster", class: "img-fluid img-index" %>
          <% elsif recommendation.podcast.image_url.start_with?("..//assets/images/") %>
            <%= image_tag recommendation.podcast.image_url.gsub("..//assets/images/", ""), alt: "Poster", class: "img-fluid img-index" %>
          <% else %>
            <%= image_tag recommendation.podcast.image_url.gsub("../assets/images/", ""), alt: "Poster", class: "img-fluid img-index" %>
          <% end %>
          </div>
            <%# <%= image_tag recommendation.movie.image_url, alt: "Poster", class: "img-fluid" %>
          <div>
            <h5 class="movies-card-header"><%=recommendation.podcast.title %></h5>
          </div>
          <div>
          <% if recommendation.friend != nil %>
            <p class="movies-card-text"><i class="fa-solid fa-user"></i>  <%=recommendation.friend%></p>
          <% end %>
          </div>
        <%end %>
      </div>
    <%end%>
  </div>
</div>

app/views/podcastrecoms/viewed.html.erb
<div class="container">
  <div class="wrapper">
    <%@podcastrecoms.select do |podcastrecom|%>
      <div class="movies-cards" style="max-width: 540px;">
        <%= link_to podcastrecom_path(podcastrecom), class:"text-decoration-none" do%>
          <div>
          <% if podcastrecom.podcast.image_url.start_with?("http") %>
            <%= image_tag podcastrecom.podcats.image_url, alt: "Poster", class: "img-fluid img-index" %>
          <% elsif podcastrecom.podcast.image_url.start_with?("..//assets/images/") %>
            <%= image_tag podcastrecom.podcast.image_url.gsub("..//assets/images/", ""), alt: "Poster", class: "img-fluid img-index" %>
          <% else %>
            <%= image_tag podcastrecom.podcast.image_url.gsub("../assets/images/", ""), alt: "Poster", class: "img-fluid img-index" %>
          <% end %>
          </div>
          <div>
            <% if podcastrecom.feedback_rating != nil %>
              <% podcastrecom.feedback_rating.times do %>
                <i class="fa-solid fa-star"></i>
              <% end %>
            <% end %>
          </div>
          <div>
            <h5 class="movies-card-text movies-card-header"><%=podcastrecom.podcast.title %></h5>
          </div>
          <div>
          <% if podcastrecom.friend != nil %>
            <p class="movies-card-text"><i class="fa-solid fa-user"></i>  <%=podcastrecom.friend%></p>
          <% end %>
          </div>
        <%end %>
      </div>
    <%end%>
  </div>
</div>